### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by marcoxa** [Shinmera/portability#12]
Hi

I am not a contributor, therefore I cannot commit to the list.  I am trying to add clast.sf.net

All the best

Marco

**Comment by Shinmera** [comment]
Send a PR!

**Comment by marcoxa** [comment]
Problem...  looks like I cannot create a PR...  I suppose bcause I do not have a GitHub version of the repo.

```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin marcoxa:master
remote: Permission to Shinmera/portability.git denied to marcoxa.
fatal: unable to access 'https://github.com/Shinmera/portability.git/': The requested URL returned error: 403
Pushing to https://github.com/Shinmera/portability.git
Completed with errors, see above.
```

**Comment by Shinmera** [comment]
Yeah, you have to create a fork first, then push to that fork and create a PR through the github interface.

**Comment by marcoxa** [comment]
Ok.  Done.

**Comment by Shinmera** [comment]
Thanks, it's been merged and should show up live in a minute!
