### ISSUE TITLE
Make Anchored Parts Highlighted

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/portability#4]
Allow putting a library or implementation into an anchor of the URL and dynamically (JS, sigh) mark up the corresponding row or column.

**Comment by Hexstream** [comment]
If you use `:target` you can do this in pure CSS for the rows at least (give each row an ID), I'm not sure if you can do something in pure CSS with `<col>`...

**Comment by Shinmera** [comment]
Ah, perfect!
